// Generated by CoffeeScript 1.4.0
(function() {

  (function($) {
    return $(function() {
      var desc;
      desc = $('.position .description').fadeOut();
      return $('.position').hover(function() {
        return $(this).siblings().find('.description').fadeOut().end().find('.description').fadeIn();
      });
    });
  })(jQuery);

}).call(this);
